### ISSUE TITLE
UniPT on NLP tasks

### ISSUE THREAD

**Issue by janjiang005** [Paranioar/UniPT#5]
Nice work! @Paranioar 
I noticed that the paper mentioned UniPT based on the T5 large model performed well on NLP tasks such as GLUE benchmark.But I didn't find the relevant code on GitHub...So could you please provide a copy of the code in NLP field?

**Comment by Paranioar** [comment]
Sorry for the late reply. I am too busy lately. I will organize it later and release it together with the [SHERL project](https://github.com/Paranioar/SHERL).
